### ISSUE TITLE
Bug Report: BytesMut 'assertion failed: self.remaining_mut() >= src.remaining()'

### ISSUE THREAD

**Issue by leoppro** [tokio-rs/bytes#266]
version : bytes = "0.4.12"

```
$ rustc --version
rustc 1.36.0-nightly (af98304b9 2019-05-11)
$ cargo --version
cargo 1.36.0-nightly (759b6161a 2019-05-06)
```

main.rs:
```
use bytes::{BufMut, Bytes, BytesMut};

fn main() {
        let key = Bytes::from("1234567890123456789");
        let mut value_key = BytesMut::from("1234567890123");
        value_key.put(key);
}
```

painc info:
```
thread 'main' panicked at 'assertion failed: self.remaining_mut() >= src.remaining()', /home/leoppro/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bytes-0.4.12/src/buf/buf_mut.rs:230:9
stack backtrace:
   0:     0x55abdbcc2bf3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::had1ef077bf7ec324
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55abdbcbeb2b - std::sys_common::backtrace::_print::h6f882ddc0cb23bba
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x55abdbcc1bd6 - std::panicking::default_hook::{{closure}}::h47bab10d9b5498ff
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x55abdbcc1969 - std::panicking::default_hook::h53275efa9b0ada2b
                               at src/libstd/panicking.rs:211
   4:     0x55abdbcc222f - std::panicking::rust_panic_with_hook::h34d4d9732505a471
                               at src/libstd/panicking.rs:474
   5:     0x55abdbcb8da7 - std::panicking::begin_panic::h9e3e0d6de2107488
                               at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/panicking.rs:408
   6:     0x55abdbcb2fa6 - bytes::buf::buf_mut::BufMut::put::h561091972764f9d9
                               at /home/leoppro/code/bytes_bug/<::std::macros::panic macros>:3
   7:     0x55abdbcb22b6 - bytes_bug::main::h6391988ef4c0a1bc
                               at src/main.rs:6
   8:     0x55abdbcb25bf - std::rt::lang_start::{{closure}}::h0aaf446b0defeb7f
                               at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/rt.rs:64
   9:     0x55abdbcc1c82 - std::panicking::try::do_call::hbe3de9b60b83c31b
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  10:     0x55abdbcc39e9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  11:     0x55abdbcc273c - std::rt::lang_start_internal::hefe5775a75294ddc
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  12:     0x55abdbcb2598 - std::rt::lang_start::hbae320cf22eee607
                               at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/rt.rs:64
  13:     0x55abdbcb2349 - main
  14:     0x7f81fb085ce2 - __libc_start_main
  15:     0x55abdbcb216d - _start
  16:                0x0 - <unknown>
```

**Comment by leoppro** [comment]
I just upgraded my rustc, this program compiled with the lastest rustc(1.37.0-nightly (d132f544f 2019-06-07)) still report errors

**Comment by seanmonstar** [comment]
This is [expected behavior in v0.4.x](https://docs.rs/bytes/0.4.12/bytes/struct.BytesMut.html#growth).

There is #170 tracking that we want to change this behavior in 0.5.
